DEPARTMENTS = [
    "AI & Machine Learning",
    "Trading Automation",
    "VPN & Network Security",
    "Web Development",
    "Mobile Applications",
    "System Integration & API",
    "Data Science & Analytics",
    "Blockchain & Cryptocurrency",
    "Graphic Design & Branding",
    "Content Creation & Copywriting",
    "Social Media Management",
    "Digital Marketing & Advertising",
    "BSTM Tutorial Center",
    "Private Security",
    "Music",
    "CabLink Transportation",
    "Finance & Accounting",
    "Marketplace & E-Commerce",
    "Research & Development",
    "Healthcare Information & Wellness",
    "Nutrition & Health Products",
    "Micro Farming & Urban Agriculture",
    "Sustainability & Environment",
    "Human Resources & Talent Development",
    "Project Management Office",
    "Legal & Compliance",
    "G.I.N - Global Intelligence Network",
    "BSTM Clothing Brand",
    "Spiritual Guidance & Consciousness",
    "BHD - Black Hole Drive"
]
